version: '3'

services:
  postgres:
    container_name: fintech_postgres
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=2654
    ports:
      - '5432:5432'

  postgres_live:
    container_name: fintech_postgres_live
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=2654
    ports:
      - '5433:5432'
